// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNUtTPcFUy2rYd2mO-I1Vzm-lLSYqFLuA',
    appId: '1:797261616667:web:bfb9fd78b5fae25d638abe',
    messagingSenderId: '797261616667',
    projectId: 'xchange-maxthethawne',
    authDomain: 'xchange-maxthethawne.firebaseapp.com',
    storageBucket: 'xchange-maxthethawne.firebasestorage.app',
    measurementId: 'G-0S6R5B3TJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszy6k_Eu1i2L1YaiCxabaWOaaTI01L4k',
    appId: '1:797261616667:android:fb068527538748ac638abe',
    messagingSenderId: '797261616667',
    projectId: 'xchange-maxthethawne',
    storageBucket: 'xchange-maxthethawne.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNUtTPcFUy2rYd2mO-I1Vzm-lLSYqFLuA',
    appId: '1:797261616667:web:15d13e11c762a4f1638abe',
    messagingSenderId: '797261616667',
    projectId: 'xchange-maxthethawne',
    authDomain: 'xchange-maxthethawne.firebaseapp.com',
    storageBucket: 'xchange-maxthethawne.firebasestorage.app',
    measurementId: 'G-0SVHHNY6EV',
  );
}
